const seaCreatures = [
{
		"#": 17,
		"Name": "abalone",
		"Sell": 2000,
		"Shadow": "Medium",
		"Movement Speed": "Medium",
		"Total Catches to Unlock": 20,
		"Spawn Rates": "1–6",
		"NH Jan": "4 PM – 9 AM",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "NA",
		"NH Jun": "4 PM – 9 AM",
		"NH Jul": "4 PM – 9 AM",
		"NH Aug": "4 PM – 9 AM",
		"NH Sep": "4 PM – 9 AM",
		"NH Oct": "4 PM – 9 AM",
		"NH Nov": "4 PM – 9 AM",
		"NH Dec": "4 PM – 9 AM",
		"SH Jan": "4 PM – 9 AM",
		"SH Feb": "4 PM – 9 AM",
		"SH Mar": "4 PM – 9 AM",
		"SH Apr": "4 PM – 9 AM",
		"SH May": "4 PM – 9 AM",
		"SH Jun": "4 PM – 9 AM",
		"SH Jul": "4 PM – 9 AM",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "NA",
		"SH Dec": "4 PM – 9 AM",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Awabi",
		"Critterpedia Filename": "DiveFishAwabi",
		"Furniture Filename": "FtrDiveFishAwabi",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2835,
		"Unique Entry ID": "LnurTYKDSPtsiQr62",
		"Type": "sea"
	},{
		"#": 28,
		"Name": "acorn barnacle",
		"Sell": 600,
		"Shadow": "X-Small",
		"Movement Speed": "Stationary",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "6–11",
		"NH Jan": "All day",
		"NH Feb": "All day",
		"NH Mar": "All day",
		"NH Apr": "All day",
		"NH May": "All day",
		"NH Jun": "All day",
		"NH Jul": "All day",
		"NH Aug": "All day",
		"NH Sep": "All day",
		"NH Oct": "All day",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "All day",
		"SH Feb": "All day",
		"SH Mar": "All day",
		"SH Apr": "All day",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "All day",
		"SH Aug": "All day",
		"SH Sep": "All day",
		"SH Oct": "All day",
		"SH Nov": "All day",
		"SH Dec": "All day",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Fujitsubo",
		"Critterpedia Filename": "DiveFishFujitsubo",
		"Furniture Filename": "FtrDiveFishFujitsubo",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2832,
		"Unique Entry ID": "QjvNJrjo5pNqZzuGq",
		"Type": "sea"
	},{
		"#": 19,
		"Name": "chambered nautilus",
		"Sell": 1800,
		"Shadow": "Medium",
		"Movement Speed": "Medium",
		"Total Catches to Unlock": 20,
		"Spawn Rates": "3–5",
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "4 PM – 9 AM",
		"NH Apr": "4 PM – 9 AM",
		"NH May": "4 PM – 9 AM",
		"NH Jun": "4 PM – 9 AM",
		"NH Jul": "NA",
		"NH Aug": "NA",
		"NH Sep": "4 PM – 9 AM",
		"NH Oct": "4 PM – 9 AM",
		"NH Nov": "4 PM – 9 AM",
		"NH Dec": "NA",
		"SH Jan": "NA",
		"SH Feb": "NA",
		"SH Mar": "4 PM – 9 AM",
		"SH Apr": "4 PM – 9 AM",
		"SH May": "4 PM – 9 AM",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "4 PM – 9 AM",
		"SH Oct": "4 PM – 9 AM",
		"SH Nov": "4 PM – 9 AM",
		"SH Dec": "4 PM – 9 AM",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Oumugai",
		"Critterpedia Filename": "DiveFishOumagai",
		"Furniture Filename": "FtrDiveFishOumagai",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2856,
		"Unique Entry ID": "cmNawSTGaZZjRi5sp",
		"Type": "sea"
	},{
		"#": 25,
		"Name": "Dungeness crab",
		"Sell": 1900,
		"Shadow": "Medium",
		"Movement Speed": "Medium",
		"Total Catches to Unlock": 20,
		"Spawn Rates": "3–5",
		"NH Jan": "All day",
		"NH Feb": "All day",
		"NH Mar": "All day",
		"NH Apr": "All day",
		"NH May": "All day",
		"NH Jun": "NA",
		"NH Jul": "NA",
		"NH Aug": "NA",
		"NH Sep": "NA",
		"NH Oct": "NA",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "NA",
		"SH Feb": "NA",
		"SH Mar": "NA",
		"SH Apr": "NA",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "All day",
		"SH Aug": "All day",
		"SH Sep": "All day",
		"SH Oct": "All day",
		"SH Nov": "All day",
		"SH Dec": "NA",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "DungenessCrab",
		"Critterpedia Filename": "DiveFishDungenessCrab",
		"Furniture Filename": "FtrDiveFishDungenessCrab",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 7308,
		"Unique Entry ID": "jTP553H6DNuKBSAKa",
		"Type": "sea"
	},{
		"#": 23,
		"Name": "firefly squid",
		"Sell": 1400,
		"Shadow": "X-Small",
		"Movement Speed": "Slow",
		"Total Catches to Unlock": 0,
		"Spawn Rates": 6,
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "9 PM – 4 AM",
		"NH Apr": "9 PM – 4 AM",
		"NH May": "9 PM – 4 AM",
		"NH Jun": "9 PM – 4 AM",
		"NH Jul": "NA",
		"NH Aug": "NA",
		"NH Sep": "NA",
		"NH Oct": "NA",
		"NH Nov": "NA",
		"NH Dec": "NA",
		"SH Jan": "NA",
		"SH Feb": "NA",
		"SH Mar": "NA",
		"SH Apr": "NA",
		"SH May": "NA",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "9 PM – 4 AM",
		"SH Oct": "9 PM – 4 AM",
		"SH Nov": "9 PM – 4 AM",
		"SH Dec": "9 PM – 4 AM",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Hotaruika",
		"Critterpedia Filename": "DiveFishHotaruika",
		"Furniture Filename": "FtrDiveFishHotaruika",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 6920,
		"Unique Entry ID": "ETuWxdyZNpqeFCYby",
		"Type": "sea"
	},{
		"#": 39,
		"Name": "flatworm",
		"Sell": 700,
		"Shadow": "X-Small",
		"Movement Speed": "Very slow",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "5–8",
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "NA",
		"NH Jun": "NA",
		"NH Jul": "NA",
		"NH Aug": "4 PM – 9 AM",
		"NH Sep": "4 PM – 9 AM",
		"NH Oct": "NA",
		"NH Nov": "NA",
		"NH Dec": "NA",
		"SH Jan": "NA",
		"SH Feb": "4 PM – 9 AM",
		"SH Mar": "4 PM – 9 AM",
		"SH Apr": "NA",
		"SH May": "NA",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "NA",
		"SH Dec": "NA",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Hiramushi",
		"Critterpedia Filename": "DiveFishHiramushi",
		"Furniture Filename": "FtrDiveFishHiramushi",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2844,
		"Unique Entry ID": "4LAq9YXXj4ZdfkSuK",
		"Type": "sea"
	},{
		"#": 24,
		"Name": "gazami crab",
		"Sell": 2200,
		"Shadow": "Medium",
		"Movement Speed": "Medium",
		"Total Catches to Unlock": 20,
		"Spawn Rates": "2–5",
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "NA",
		"NH Jun": "All day",
		"NH Jul": "All day",
		"NH Aug": "All day",
		"NH Sep": "All day",
		"NH Oct": "All day",
		"NH Nov": "All day",
		"NH Dec": "NA",
		"SH Jan": "All day",
		"SH Feb": "All day",
		"SH Mar": "All day",
		"SH Apr": "All day",
		"SH May": "All day",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "NA",
		"SH Dec": "All day",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Gazami",
		"Critterpedia Filename": "DiveFishGazami",
		"Furniture Filename": "FtrDiveFishGazami",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 7191,
		"Unique Entry ID": "ruLaEghgv3y3obBA2",
		"Type": "sea"
	},{
		"#": 35,
		"Name": "giant isopod",
		"Sell": 12000,
		"Shadow": "Medium",
		"Movement Speed": "Very fast",
		"Total Catches to Unlock": 80,
		"Spawn Rates": 1,
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "NA",
		"NH Jun": "NA",
		"NH Jul": "9 AM – 4 PM; 9 PM – 4 AM",
		"NH Aug": "9 AM – 4 PM; 9 PM – 4 AM",
		"NH Sep": "9 AM – 4 PM; 9 PM – 4 AM",
		"NH Oct": "9 AM – 4 PM; 9 PM – 4 AM",
		"NH Nov": "NA",
		"NH Dec": "NA",
		"SH Jan": "9 AM – 4 PM; 9 PM – 4 AM",
		"SH Feb": "9 AM – 4 PM; 9 PM – 4 AM",
		"SH Mar": "9 AM – 4 PM; 9 PM – 4 AM",
		"SH Apr": "9 AM – 4 PM; 9 PM – 4 AM",
		"SH May": "NA",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "NA",
		"SH Dec": "NA",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "No lighting",
		"Icon Filename": "Daiougusokumushi",
		"Critterpedia Filename": "DiveFishDaiougusokumushi",
		"Furniture Filename": "FtrDiveFishDaiougusokumushi",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2858,
		"Unique Entry ID": "eGLoSDD4EWD2c6SGs",
		"Type": "sea"
	},{
		"#": 18,
		"Name": "gigas giant clam",
		"Sell": 15000,
		"Shadow": "X-Large",
		"Movement Speed": "Very fast",
		"Total Catches to Unlock": 80,
		"Spawn Rates": 1,
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "All day",
		"NH Jun": "All day",
		"NH Jul": "All day",
		"NH Aug": "All day",
		"NH Sep": "All day",
		"NH Oct": "NA",
		"NH Nov": "NA",
		"NH Dec": "NA",
		"SH Jan": "All day",
		"SH Feb": "All day",
		"SH Mar": "All day",
		"SH Apr": "NA",
		"SH May": "NA",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "All day",
		"SH Dec": "All day",
		"Size": "2x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Shakogai",
		"Critterpedia Filename": "DiveFishShakogai",
		"Furniture Filename": "FtrDiveFishShakogai",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 7214,
		"Unique Entry ID": "EQmRaHjokMEGTDC7G",
		"Type": "sea"
	},{
		"#": 36,
		"Name": "horseshoe crab",
		"Sell": 2500,
		"Shadow": "Medium",
		"Movement Speed": "Medium",
		"Total Catches to Unlock": 20,
		"Spawn Rates": "3–5",
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "NA",
		"NH Jun": "NA",
		"NH Jul": "9 PM – 4 AM",
		"NH Aug": "9 PM – 4 AM",
		"NH Sep": "9 PM – 4 AM",
		"NH Oct": "NA",
		"NH Nov": "NA",
		"NH Dec": "NA",
		"SH Jan": "9 PM – 4 AM",
		"SH Feb": "9 PM – 4 AM",
		"SH Mar": "9 PM – 4 AM",
		"SH Apr": "NA",
		"SH May": "NA",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "NA",
		"SH Dec": "NA",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "No lighting",
		"Icon Filename": "Kabutogani",
		"Critterpedia Filename": "DiveFishKabutogani",
		"Furniture Filename": "FtrDiveFishKabutogani",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2857,
		"Unique Entry ID": "bbhHaiT2qwcTy46X5",
		"Type": "sea"
	},{
		"#": 34,
		"Name": "lobster",
		"Sell": 4500,
		"Shadow": "Large",
		"Movement Speed": "Fast",
		"Total Catches to Unlock": 40,
		"Spawn Rates": "1–2",
		"NH Jan": "All day",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "All day",
		"NH May": "All day",
		"NH Jun": "All day",
		"NH Jul": "NA",
		"NH Aug": "NA",
		"NH Sep": "NA",
		"NH Oct": "NA",
		"NH Nov": "NA",
		"NH Dec": "All day",
		"SH Jan": "NA",
		"SH Feb": "NA",
		"SH Mar": "NA",
		"SH Apr": "NA",
		"SH May": "NA",
		"SH Jun": "All day",
		"SH Jul": "All day",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "All day",
		"SH Nov": "All day",
		"SH Dec": "All day",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Fish54",
		"Critterpedia Filename": "DiveFishLobster",
		"Furniture Filename": "FtrDiveFishLobster",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2849,
		"Unique Entry ID": "5DadWMEddJREFyXKo",
		"Type": "sea"
	},{
		"#": 32,
		"Name": "mantis shrimp",
		"Sell": 2500,
		"Shadow": "Small",
		"Movement Speed": "Medium",
		"Total Catches to Unlock": 20,
		"Spawn Rates": "2–8",
		"NH Jan": "4 PM – 9 AM",
		"NH Feb": "4 PM – 9 AM",
		"NH Mar": "4 PM – 9 AM",
		"NH Apr": "4 PM – 9 AM",
		"NH May": "4 PM – 9 AM",
		"NH Jun": "4 PM – 9 AM",
		"NH Jul": "4 PM – 9 AM",
		"NH Aug": "4 PM – 9 AM",
		"NH Sep": "4 PM – 9 AM",
		"NH Oct": "4 PM – 9 AM",
		"NH Nov": "4 PM – 9 AM",
		"NH Dec": "4 PM – 9 AM",
		"SH Jan": "4 PM – 9 AM",
		"SH Feb": "4 PM – 9 AM",
		"SH Mar": "4 PM – 9 AM",
		"SH Apr": "4 PM – 9 AM",
		"SH May": "4 PM – 9 AM",
		"SH Jun": "4 PM – 9 AM",
		"SH Jul": "4 PM – 9 AM",
		"SH Aug": "4 PM – 9 AM",
		"SH Sep": "4 PM – 9 AM",
		"SH Oct": "4 PM – 9 AM",
		"SH Nov": "4 PM – 9 AM",
		"SH Dec": "4 PM – 9 AM",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Shako",
		"Critterpedia Filename": "DiveFishSyako",
		"Furniture Filename": "FtrDiveFishSyako",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2845,
		"Unique Entry ID": "WvZWyzkotj6WQ3tLy",
		"Type": "sea"
	},{
		"#": 9,
		"Name": "moon jellyfish",
		"Sell": 600,
		"Shadow": "Small",
		"Movement Speed": "Very slow",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "4–12",
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "NA",
		"NH Jun": "NA",
		"NH Jul": "All day",
		"NH Aug": "All day",
		"NH Sep": "All day",
		"NH Oct": "NA",
		"NH Nov": "NA",
		"NH Dec": "NA",
		"SH Jan": "All day",
		"SH Feb": "All day",
		"SH Mar": "All day",
		"SH Apr": "NA",
		"SH May": "NA",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "NA",
		"SH Dec": "NA",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Mizukurage",
		"Critterpedia Filename": "DiveFishMizukurage",
		"Furniture Filename": "FtrDiveFishMizukurage",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 7245,
		"Unique Entry ID": "iugx8EqNWqiwv73C7",
		"Type": "sea"
	},{
		"#": 12,
		"Name": "mussel",
		"Sell": 1500,
		"Shadow": "Small",
		"Movement Speed": "Slow",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "3–8",
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "NA",
		"NH Jun": "All day",
		"NH Jul": "All day",
		"NH Aug": "All day",
		"NH Sep": "All day",
		"NH Oct": "All day",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "All day",
		"SH Feb": "All day",
		"SH Mar": "All day",
		"SH Apr": "All day",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "NA",
		"SH Dec": "All day",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "No lighting",
		"Icon Filename": "Muhrugai",
		"Critterpedia Filename": "DiveFishMuhrugai",
		"Furniture Filename": "FtrDiveFishMuhrugai",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 7411,
		"Unique Entry ID": "M784h47XqSbBSthgT",
		"Type": "sea"
	},{
		"#": 20,
		"Name": "octopus",
		"Sell": 1200,
		"Shadow": "Medium",
		"Movement Speed": "Slow",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "2–8",
		"NH Jan": "All day",
		"NH Feb": "All day",
		"NH Mar": "All day",
		"NH Apr": "All day",
		"NH May": "All day",
		"NH Jun": "All day",
		"NH Jul": "All day",
		"NH Aug": "All day",
		"NH Sep": "All day",
		"NH Oct": "All day",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "All day",
		"SH Feb": "All day",
		"SH Mar": "All day",
		"SH Apr": "All day",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "All day",
		"SH Aug": "All day",
		"SH Sep": "All day",
		"SH Oct": "All day",
		"SH Nov": "All day",
		"SH Dec": "All day",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Tako",
		"Critterpedia Filename": "DiveFishTako",
		"Furniture Filename": "FtrDiveFishTako",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2854,
		"Unique Entry ID": "f7amqwd7b3fHnvPFA",
		"Type": "sea"
	},{
		"#": 13,
		"Name": "oyster",
		"Sell": 1100,
		"Shadow": "Small",
		"Movement Speed": "Slow",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "5–12",
		"NH Jan": "All day",
		"NH Feb": "All day",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "NA",
		"NH Jun": "NA",
		"NH Jul": "NA",
		"NH Aug": "NA",
		"NH Sep": "All day",
		"NH Oct": "All day",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "NA",
		"SH Feb": "NA",
		"SH Mar": "All day",
		"SH Apr": "All day",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "All day",
		"SH Aug": "All day",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "NA",
		"SH Dec": "NA",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "No lighting",
		"Icon Filename": "Kaki",
		"Critterpedia Filename": "DiveFishOyster",
		"Furniture Filename": "FtrDiveFishKaki",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2833,
		"Unique Entry ID": "aacYapCp5wKdQDCmB",
		"Type": "sea"
	},{
		"#": 11,
		"Name": "pearl oyster",
		"Sell": 2800,
		"Shadow": "Small",
		"Movement Speed": "Medium",
		"Total Catches to Unlock": 20,
		"Spawn Rates": "2–4",
		"NH Jan": "All day",
		"NH Feb": "All day",
		"NH Mar": "All day",
		"NH Apr": "All day",
		"NH May": "All day",
		"NH Jun": "All day",
		"NH Jul": "All day",
		"NH Aug": "All day",
		"NH Sep": "All day",
		"NH Oct": "All day",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "All day",
		"SH Feb": "All day",
		"SH Mar": "All day",
		"SH Apr": "All day",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "All day",
		"SH Aug": "All day",
		"SH Sep": "All day",
		"SH Oct": "All day",
		"SH Nov": "All day",
		"SH Dec": "All day",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "No lighting",
		"Icon Filename": "Akoyagai",
		"Critterpedia Filename": "DiveFishAkoyagai",
		"Furniture Filename": "FtrDiveFishAkoyagai",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2838,
		"Unique Entry ID": "Hr2jZ9XybS3jYFw8H",
		"Type": "sea"
	},{
		"#": 27,
		"Name": "red king crab",
		"Sell": 8000,
		"Shadow": "Large",
		"Movement Speed": "Very fast",
		"Total Catches to Unlock": 80,
		"Spawn Rates": "1–2",
		"NH Jan": "All day",
		"NH Feb": "All day",
		"NH Mar": "All day",
		"NH Apr": "NA",
		"NH May": "NA",
		"NH Jun": "NA",
		"NH Jul": "NA",
		"NH Aug": "NA",
		"NH Sep": "NA",
		"NH Oct": "NA",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "NA",
		"SH Feb": "NA",
		"SH Mar": "NA",
		"SH Apr": "NA",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "All day",
		"SH Aug": "All day",
		"SH Sep": "All day",
		"SH Oct": "NA",
		"SH Nov": "NA",
		"SH Dec": "NA",
		"Size": "2x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Tarabagani",
		"Critterpedia Filename": "DiveFishTarabagani",
		"Furniture Filename": "FtrDiveFishTarabagani",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2852,
		"Unique Entry ID": "F3XTwHJQcfdrJk4vk",
		"Type": "sea"
	},{
		"#": 14,
		"Name": "scallop",
		"Sell": 1200,
		"Shadow": "Medium",
		"Movement Speed": "Slow",
		"Total Catches to Unlock": 5,
		"Spawn Rates": "6–8",
		"NH Jan": "All day",
		"NH Feb": "All day",
		"NH Mar": "All day",
		"NH Apr": "All day",
		"NH May": "All day",
		"NH Jun": "All day",
		"NH Jul": "All day",
		"NH Aug": "All day",
		"NH Sep": "All day",
		"NH Oct": "All day",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "All day",
		"SH Feb": "All day",
		"SH Mar": "All day",
		"SH Apr": "All day",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "All day",
		"SH Aug": "All day",
		"SH Sep": "All day",
		"SH Oct": "All day",
		"SH Nov": "All day",
		"SH Dec": "All day",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Hotate",
		"Critterpedia Filename": "DiveFishHotate",
		"Furniture Filename": "FtrDiveFishHotate",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2839,
		"Unique Entry ID": "fMwWEu3Zwy6tZdX2X",
		"Type": "sea"
	},{
		"#": 8,
		"Name": "sea anemone",
		"Sell": 500,
		"Shadow": "Large",
		"Movement Speed": "Stationary",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "3–14",
		"NH Jan": "All day",
		"NH Feb": "All day",
		"NH Mar": "All day",
		"NH Apr": "All day",
		"NH May": "All day",
		"NH Jun": "All day",
		"NH Jul": "All day",
		"NH Aug": "All day",
		"NH Sep": "All day",
		"NH Oct": "All day",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "All day",
		"SH Feb": "All day",
		"SH Mar": "All day",
		"SH Apr": "All day",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "All day",
		"SH Aug": "All day",
		"SH Sep": "All day",
		"SH Oct": "All day",
		"SH Nov": "All day",
		"SH Dec": "All day",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Isogintyaku",
		"Critterpedia Filename": "DiveFishIsogintyaku",
		"Furniture Filename": "FtrDiveFishIsogintyaku",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2840,
		"Unique Entry ID": "fre7kn6ALvnpnH8yC",
		"Type": "sea"
	},{
		"#": 3,
		"Name": "sea cucumber",
		"Sell": 500,
		"Shadow": "Medium",
		"Movement Speed": "Very slow",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "4–12",
		"NH Jan": "All day",
		"NH Feb": "All day",
		"NH Mar": "All day",
		"NH Apr": "All day",
		"NH May": "NA",
		"NH Jun": "NA",
		"NH Jul": "NA",
		"NH Aug": "NA",
		"NH Sep": "NA",
		"NH Oct": "NA",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "NA",
		"SH Feb": "NA",
		"SH Mar": "NA",
		"SH Apr": "NA",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "All day",
		"SH Aug": "All day",
		"SH Sep": "All day",
		"SH Oct": "All day",
		"SH Nov": "NA",
		"SH Dec": "NA",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Namako",
		"Critterpedia Filename": "DiveFishNamako",
		"Furniture Filename": "FtrDiveFishNamako",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2842,
		"Unique Entry ID": "2jxxcGooLMwyyiNQc",
		"Type": "sea"
	},{
		"#": 2,
		"Name": "sea grapes",
		"Sell": 900,
		"Shadow": "Small",
		"Movement Speed": "Stationary",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "4–12",
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "NA",
		"NH Jun": "All day",
		"NH Jul": "All day",
		"NH Aug": "All day",
		"NH Sep": "All day",
		"NH Oct": "NA",
		"NH Nov": "NA",
		"NH Dec": "NA",
		"SH Jan": "All day",
		"SH Feb": "All day",
		"SH Mar": "All day",
		"SH Apr": "NA",
		"SH May": "NA",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "NA",
		"SH Dec": "All day",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Umibudou",
		"Critterpedia Filename": "DiveFishUmibudou",
		"Furniture Filename": "FtrDiveFishUmibudou",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2830,
		"Unique Entry ID": "eBdtw3eCrMuP9LWyn",
		"Type": "sea"
	},{
		"#": 4,
		"Name": "sea pig",
		"Sell": 10000,
		"Shadow": "Small",
		"Movement Speed": "Very fast",
		"Total Catches to Unlock": 80,
		"Spawn Rates": 1,
		"NH Jan": "4 PM – 9 AM",
		"NH Feb": "4 PM – 9 AM",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "NA",
		"NH Jun": "NA",
		"NH Jul": "NA",
		"NH Aug": "NA",
		"NH Sep": "NA",
		"NH Oct": "NA",
		"NH Nov": "4 PM – 9 AM",
		"NH Dec": "4 PM – 9 AM",
		"SH Jan": "NA",
		"SH Feb": "NA",
		"SH Mar": "NA",
		"SH Apr": "NA",
		"SH May": "4 PM – 9 AM",
		"SH Jun": "4 PM – 9 AM",
		"SH Jul": "4 PM – 9 AM",
		"SH Aug": "4 PM – 9 AM",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "NA",
		"SH Dec": "NA",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Senjunamako",
		"Critterpedia Filename": "DiveFishSenjunamako",
		"Furniture Filename": "FtrDiveFishSenjunamako",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 7303,
		"Unique Entry ID": "kxxguvYvS4G3o7E5x",
		"Type": "sea"
	},{
		"#": 37,
		"Name": "sea pineapple",
		"Sell": 1500,
		"Shadow": "Small",
		"Movement Speed": "Slow",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "2–6",
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "All day",
		"NH May": "All day",
		"NH Jun": "All day",
		"NH Jul": "All day",
		"NH Aug": "All day",
		"NH Sep": "NA",
		"NH Oct": "NA",
		"NH Nov": "NA",
		"NH Dec": "NA",
		"SH Jan": "All day",
		"SH Feb": "All day",
		"SH Mar": "NA",
		"SH Apr": "NA",
		"SH May": "NA",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "All day",
		"SH Nov": "All day",
		"SH Dec": "All day",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Hoya",
		"Critterpedia Filename": "DiveFishHoya",
		"Furniture Filename": "FtrDiveFishHoya",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 7228,
		"Unique Entry ID": "e29uLe7tkErhipLfS",
		"Type": "sea"
	},{
		"#": 10,
		"Name": "sea slug",
		"Sell": 600,
		"Shadow": "X-Small",
		"Movement Speed": "Very slow",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "1–12",
		"NH Jan": "All day",
		"NH Feb": "All day",
		"NH Mar": "All day",
		"NH Apr": "All day",
		"NH May": "All day",
		"NH Jun": "All day",
		"NH Jul": "All day",
		"NH Aug": "All day",
		"NH Sep": "All day",
		"NH Oct": "All day",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "All day",
		"SH Feb": "All day",
		"SH Mar": "All day",
		"SH Apr": "All day",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "All day",
		"SH Aug": "All day",
		"SH Sep": "All day",
		"SH Oct": "All day",
		"SH Nov": "All day",
		"SH Dec": "All day",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Umiushi",
		"Critterpedia Filename": "DiveFishUmiushi",
		"Furniture Filename": "FtrDiveFishUmiushi",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2843,
		"Unique Entry ID": "3YjdEG93fagcXpiuf",
		"Type": "sea"
	},{
		"#": 5,
		"Name": "sea star",
		"Sell": 500,
		"Shadow": "Small",
		"Movement Speed": "Very slow",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "4–10",
		"NH Jan": "All day",
		"NH Feb": "All day",
		"NH Mar": "All day",
		"NH Apr": "All day",
		"NH May": "All day",
		"NH Jun": "All day",
		"NH Jul": "All day",
		"NH Aug": "All day",
		"NH Sep": "All day",
		"NH Oct": "All day",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "All day",
		"SH Feb": "All day",
		"SH Mar": "All day",
		"SH Apr": "All day",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "All day",
		"SH Aug": "All day",
		"SH Sep": "All day",
		"SH Oct": "All day",
		"SH Nov": "All day",
		"SH Dec": "All day",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Hitode",
		"Critterpedia Filename": "DiveFishHitode",
		"Furniture Filename": "FtrDiveFishHitode",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2841,
		"Unique Entry ID": "vAF9BcZt5q8gBQJmj",
		"Type": "sea"
	},{
		"#": 6,
		"Name": "sea urchin",
		"Sell": 1700,
		"Shadow": "Small",
		"Movement Speed": "Slow",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "2–7",
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "All day",
		"NH Jun": "All day",
		"NH Jul": "All day",
		"NH Aug": "All day",
		"NH Sep": "All day",
		"NH Oct": "NA",
		"NH Nov": "NA",
		"NH Dec": "NA",
		"SH Jan": "All day",
		"SH Feb": "All day",
		"SH Mar": "All day",
		"SH Apr": "NA",
		"SH May": "NA",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "All day",
		"SH Dec": "All day",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "No lighting",
		"Icon Filename": "Uni",
		"Critterpedia Filename": "DiveFishUni",
		"Furniture Filename": "FtrDiveFishUni",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2831,
		"Unique Entry ID": "3emjFCipv2bgQ6HaM",
		"Type": "sea"
	},{
		"#": 1,
		"Name": "seaweed",
		"Sell": 600,
		"Shadow": "Large",
		"Movement Speed": "Stationary",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "3–14",
		"NH Jan": "All day",
		"NH Feb": "All day",
		"NH Mar": "All day",
		"NH Apr": "All day",
		"NH May": "All day",
		"NH Jun": "All day",
		"NH Jul": "All day",
		"NH Aug": "NA",
		"NH Sep": "NA",
		"NH Oct": "All day",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "All day",
		"SH Feb": "NA",
		"SH Mar": "NA",
		"SH Apr": "All day",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "All day",
		"SH Aug": "All day",
		"SH Sep": "All day",
		"SH Oct": "All day",
		"SH Nov": "All day",
		"SH Dec": "All day",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "No lighting",
		"Icon Filename": "Wakame",
		"Critterpedia Filename": "DiveFishWakame",
		"Furniture Filename": "FtrDiveFishWakame",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2620,
		"Unique Entry ID": "KM4dfXCZ6CvZjEyw9",
		"Type": "sea"
	},{
		"#": 7,
		"Name": "slate pencil urchin",
		"Sell": 2000,
		"Shadow": "Medium",
		"Movement Speed": "Medium",
		"Total Catches to Unlock": 20,
		"Spawn Rates": "3–4",
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "4 PM – 9 AM",
		"NH Jun": "4 PM – 9 AM",
		"NH Jul": "4 PM – 9 AM",
		"NH Aug": "4 PM – 9 AM",
		"NH Sep": "4 PM – 9 AM",
		"NH Oct": "NA",
		"NH Nov": "NA",
		"NH Dec": "NA",
		"SH Jan": "4 PM – 9 AM",
		"SH Feb": "4 PM – 9 AM",
		"SH Mar": "4 PM – 9 AM",
		"SH Apr": "NA",
		"SH May": "NA",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "4 PM – 9 AM",
		"SH Dec": "4 PM – 9 AM",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Paipuuni",
		"Critterpedia Filename": "DiveFishPaipuuni",
		"Furniture Filename": "FtrDiveFishPaipuuni",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 7267,
		"Unique Entry ID": "TMftNBRmEGkvhpfnC",
		"Type": "sea"
	},{
		"#": 26,
		"Name": "snow crab",
		"Sell": 6000,
		"Shadow": "Large",
		"Movement Speed": "Fast",
		"Total Catches to Unlock": 40,
		"Spawn Rates": "1–3",
		"NH Jan": "All day",
		"NH Feb": "All day",
		"NH Mar": "All day",
		"NH Apr": "All day",
		"NH May": "NA",
		"NH Jun": "NA",
		"NH Jul": "NA",
		"NH Aug": "NA",
		"NH Sep": "NA",
		"NH Oct": "NA",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "NA",
		"SH Feb": "NA",
		"SH Mar": "NA",
		"SH Apr": "NA",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "All day",
		"SH Aug": "All day",
		"SH Sep": "All day",
		"SH Oct": "All day",
		"SH Nov": "NA",
		"SH Dec": "NA",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "No lighting",
		"Icon Filename": "Zuwaigani",
		"Critterpedia Filename": "DiveFishZuwaigani",
		"Furniture Filename": "FtrDiveFishZuwaigani",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2850,
		"Unique Entry ID": "bQNma5vbcs7wWRqY7",
		"Type": "sea"
	},{
		"#": 29,
		"Name": "spider crab",
		"Sell": 12000,
		"Shadow": "X-Large",
		"Movement Speed": "Very fast",
		"Total Catches to Unlock": 80,
		"Spawn Rates": "1–2",
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "All day",
		"NH Apr": "All day",
		"NH May": "NA",
		"NH Jun": "NA",
		"NH Jul": "NA",
		"NH Aug": "NA",
		"NH Sep": "NA",
		"NH Oct": "NA",
		"NH Nov": "NA",
		"NH Dec": "NA",
		"SH Jan": "NA",
		"SH Feb": "NA",
		"SH Mar": "NA",
		"SH Apr": "NA",
		"SH May": "NA",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "All day",
		"SH Oct": "All day",
		"SH Nov": "NA",
		"SH Dec": "NA",
		"Size": "2x2",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "No lighting",
		"Icon Filename": "Takaashigani",
		"Critterpedia Filename": "DiveFishTakaashigani",
		"Furniture Filename": "FtrDiveFishTakaashigani",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2853,
		"Unique Entry ID": "gp2XNvGKNGmR6buT3",
		"Type": "sea"
	},{
		"#": 33,
		"Name": "spiny lobster",
		"Sell": 5000,
		"Shadow": "Large",
		"Movement Speed": "Fast",
		"Total Catches to Unlock": 40,
		"Spawn Rates": 5,
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "NA",
		"NH Jun": "NA",
		"NH Jul": "NA",
		"NH Aug": "NA",
		"NH Sep": "NA",
		"NH Oct": "9 PM – 4 AM",
		"NH Nov": "9 PM – 4 AM",
		"NH Dec": "9 PM – 4 AM",
		"SH Jan": "NA",
		"SH Feb": "NA",
		"SH Mar": "NA",
		"SH Apr": "9 PM – 4 AM",
		"SH May": "9 PM – 4 AM",
		"SH Jun": "9 PM – 4 AM",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "NA",
		"SH Dec": "NA",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "No lighting",
		"Icon Filename": "Iseebi",
		"Critterpedia Filename": "DiveFishIseebi",
		"Furniture Filename": "FtrDiveFishIseebi",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2848,
		"Unique Entry ID": "9n5iphC8vQe6Rar72",
		"Type": "sea"
	},{
		"#": 38,
		"Name": "spotted garden eel",
		"Sell": 1100,
		"Shadow": "Small",
		"Movement Speed": "Slow",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "6–8",
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "4 AM – 9 PM",
		"NH Jun": "4 AM – 9 PM",
		"NH Jul": "4 AM – 9 PM",
		"NH Aug": "4 AM – 9 PM",
		"NH Sep": "4 AM – 9 PM",
		"NH Oct": "4 AM – 9 PM",
		"NH Nov": "NA",
		"NH Dec": "NA",
		"SH Jan": "4 AM – 9 PM",
		"SH Feb": "4 AM – 9 PM",
		"SH Mar": "4 AM – 9 PM",
		"SH Apr": "4 AM – 9 PM",
		"SH May": "NA",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "4 AM – 9 PM",
		"SH Dec": "4 AM – 9 PM",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Chinanago",
		"Critterpedia Filename": "DiveFishChinanago",
		"Furniture Filename": "FtrDiveFishChinanago",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2855,
		"Unique Entry ID": "zYEHNF5Svak8ZARMW",
		"Type": "sea"
	},{
		"#": 31,
		"Name": "sweet shrimp",
		"Sell": 1400,
		"Shadow": "Small",
		"Movement Speed": "Slow",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "3–12",
		"NH Jan": "4 PM – 9 AM",
		"NH Feb": "4 PM – 9 AM",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "NA",
		"NH Jun": "NA",
		"NH Jul": "NA",
		"NH Aug": "NA",
		"NH Sep": "4 PM – 9 AM",
		"NH Oct": "4 PM – 9 AM",
		"NH Nov": "4 PM – 9 AM",
		"NH Dec": "4 PM – 9 AM",
		"SH Jan": "NA",
		"SH Feb": "NA",
		"SH Mar": "4 PM – 9 AM",
		"SH Apr": "4 PM – 9 AM",
		"SH May": "4 PM – 9 AM",
		"SH Jun": "4 PM – 9 AM",
		"SH Jul": "4 PM – 9 AM",
		"SH Aug": "4 PM – 9 AM",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "NA",
		"SH Dec": "NA",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Amaebi",
		"Critterpedia Filename": "DiveFishAmaebi",
		"Furniture Filename": "FtrDiveFishAmaebi",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2846,
		"Unique Entry ID": "5v5X2ipAYLaALxMsw",
		"Type": "sea"
	},{
		"#": 30,
		"Name": "tiger prawn",
		"Sell": 3000,
		"Shadow": "Small",
		"Movement Speed": "Medium",
		"Total Catches to Unlock": 20,
		"Spawn Rates": "1–4",
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "NA",
		"NH Jun": "4 PM – 9 AM",
		"NH Jul": "4 PM – 9 AM",
		"NH Aug": "4 PM – 9 AM",
		"NH Sep": "4 PM – 9 AM",
		"NH Oct": "NA",
		"NH Nov": "NA",
		"NH Dec": "NA",
		"SH Jan": "4 PM – 9 AM",
		"SH Feb": "4 PM – 9 AM",
		"SH Mar": "4 PM – 9 AM",
		"SH Apr": "NA",
		"SH May": "NA",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "NA",
		"SH Dec": "4 PM – 9 AM",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Kurumaebi",
		"Critterpedia Filename": "DiveFishKurumaebi",
		"Furniture Filename": "FtrDiveFishKurumaebi",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2847,
		"Unique Entry ID": "EaMd8ansu3qtzAGbv",
		"Type": "sea"
	},{
		"#": 16,
		"Name": "turban shell",
		"Sell": 1000,
		"Shadow": "Small",
		"Movement Speed": "Slow",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "2–10",
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "All day",
		"NH Apr": "All day",
		"NH May": "All day",
		"NH Jun": "NA",
		"NH Jul": "NA",
		"NH Aug": "NA",
		"NH Sep": "All day",
		"NH Oct": "All day",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "NA",
		"SH Feb": "NA",
		"SH Mar": "All day",
		"SH Apr": "All day",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "All day",
		"SH Oct": "All day",
		"SH Nov": "All day",
		"SH Dec": "NA",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "No lighting",
		"Icon Filename": "Sazae",
		"Critterpedia Filename": "DiveFishSazae",
		"Furniture Filename": "FtrDiveFishSazae",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 2834,
		"Unique Entry ID": "efXQqEuT2yZApwmGB",
		"Type": "sea"
	},{
		"#": 21,
		"Name": "umbrella octopus",
		"Sell": 6000,
		"Shadow": "Small",
		"Movement Speed": "Fast",
		"Total Catches to Unlock": 40,
		"Spawn Rates": "1–3",
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "All day",
		"NH Apr": "All day",
		"NH May": "All day",
		"NH Jun": "NA",
		"NH Jul": "NA",
		"NH Aug": "NA",
		"NH Sep": "All day",
		"NH Oct": "All day",
		"NH Nov": "All day",
		"NH Dec": "NA",
		"SH Jan": "NA",
		"SH Feb": "NA",
		"SH Mar": "All day",
		"SH Apr": "All day",
		"SH May": "All day",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "All day",
		"SH Oct": "All day",
		"SH Nov": "All day",
		"SH Dec": "NA",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Mendako",
		"Critterpedia Filename": "DiveFishMendako",
		"Furniture Filename": "FtrDiveFishMendako",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 7252,
		"Unique Entry ID": "kXFeaEJCCEkQ58T2e",
		"Type": "sea"
	},{
		"#": 22,
		"Name": "vampire squid",
		"Sell": 10000,
		"Shadow": "Medium",
		"Movement Speed": "Very fast",
		"Total Catches to Unlock": 80,
		"Spawn Rates": 1,
		"NH Jan": "NA",
		"NH Feb": "NA",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "4 PM – 9 AM",
		"NH Jun": "4 PM – 9 AM",
		"NH Jul": "4 PM – 9 AM",
		"NH Aug": "4 PM – 9 AM",
		"NH Sep": "NA",
		"NH Oct": "NA",
		"NH Nov": "NA",
		"NH Dec": "NA",
		"SH Jan": "4 PM – 9 AM",
		"SH Feb": "4 PM – 9 AM",
		"SH Mar": "NA",
		"SH Apr": "NA",
		"SH May": "NA",
		"SH Jun": "NA",
		"SH Jul": "NA",
		"SH Aug": "NA",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "4 PM – 9 AM",
		"SH Dec": "4 PM – 9 AM",
		"Size": "1x1",
		"Surface": "No",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Koumoridako",
		"Critterpedia Filename": "DiveFishKoumoridako",
		"Furniture Filename": "FtrDiveFishKoumoridako",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 7203,
		"Unique Entry ID": "deJZZk2rxAnePwfzq",
		"Type": "sea"
	},{
		"#": 40,
		"Name": "Venus' flower basket",
		"Sell": 5000,
		"Shadow": "Medium",
		"Movement Speed": "Fast",
		"Total Catches to Unlock": 40,
		"Spawn Rates": "1–3",
		"NH Jan": "All day",
		"NH Feb": "All day",
		"NH Mar": "NA",
		"NH Apr": "NA",
		"NH May": "NA",
		"NH Jun": "NA",
		"NH Jul": "NA",
		"NH Aug": "NA",
		"NH Sep": "NA",
		"NH Oct": "All day",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "NA",
		"SH Feb": "NA",
		"SH Mar": "NA",
		"SH Apr": "All day",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "All day",
		"SH Aug": "All day",
		"SH Sep": "NA",
		"SH Oct": "NA",
		"SH Nov": "NA",
		"SH Dec": "NA",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Kairoudouketsu",
		"Critterpedia Filename": "DiveFishKairoudouketsu",
		"Furniture Filename": "FtrDiveFishKairoudouketsu",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 7318,
		"Unique Entry ID": "mSvTRhay8tmGXseMt",
		"Type": "sea"
	},{
		"#": 15,
		"Name": "whelk",
		"Sell": 1000,
		"Shadow": "Small",
		"Movement Speed": "Slow",
		"Total Catches to Unlock": 0,
		"Spawn Rates": "1–8",
		"NH Jan": "All day",
		"NH Feb": "All day",
		"NH Mar": "All day",
		"NH Apr": "All day",
		"NH May": "All day",
		"NH Jun": "All day",
		"NH Jul": "All day",
		"NH Aug": "All day",
		"NH Sep": "All day",
		"NH Oct": "All day",
		"NH Nov": "All day",
		"NH Dec": "All day",
		"SH Jan": "All day",
		"SH Feb": "All day",
		"SH Mar": "All day",
		"SH Apr": "All day",
		"SH May": "All day",
		"SH Jun": "All day",
		"SH Jul": "All day",
		"SH Aug": "All day",
		"SH Sep": "All day",
		"SH Oct": "All day",
		"SH Nov": "All day",
		"SH Dec": "All day",
		"Size": "1x1",
		"Surface": "Yes",
		"HHA Base Points": 0,
		"Color 1": "None",
		"Color 2": "None",
		"Lighting Type": "Fluorescent",
		"Icon Filename": "Baigai",
		"Critterpedia Filename": "DiveFishBaigai",
		"Furniture Filename": "FtrDiveFishBaigai",
		"Version Added": "1.3.0",
		"Version Unlocked": "1.3.0",
		"Internal ID": 7278,
		"Unique Entry ID": "jSidvLMAXdiDAQNs6",
		"Type": "sea"
	}
]
export default seaCreatures;