const InputActionTypes = {
  HEMI_CHANGE: 'HEMI_CHANGE',
  SEARCH_CHANGE: 'SEARCH_CHANGE',
  LIST_CHANGE: 'LIST_CHANGE',
  TIME_CHANGE: 'TIME_CHANGE',
  SECOND_TIME_CHANGE: 'SECOND_TIME_CHANGE',
  MONTH_CHANGE: 'MONTH_CHANGE',
  SECOND_MONTH_CHANGE: 'SECOND_MONTH_CHANGE',
  SORT_CHANGE: 'SORT_CHANGE',
  ORDER_CHANGE: 'ORDER_CHANGE',
  TIME_FRAME_CHANGE: 'TIME_FRAME_CHANGE',
  RESET_TIME_INPUT: 'RESET_TIME_INPUT'
}

export default InputActionTypes;