const InputActionTypes = {
  HEMI_CHANGE: 'HEMI_CHANGE',
  SEARCH_CHANGE: 'SEARCH_CHANGE',
  LIST_CHANGE: 'LIST_CHANGE',
  TIME_CHANGE: 'TIME_CHANGE',
  MONTH_CHANGE: 'MONTH_CHANGE',
  SORT_CHANGE: 'SORT_CHANGE',
  ORDER_CHANGE: 'ORDER_CHANGE',
  TIME_FRAME_CHANGE: 'TIME_FRAME_CHANGE'
}

export default InputActionTypes;